# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uimain.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(744, 600)
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(280, 330, 71, 31))
        self.start.setMouseTracking(False)
        self.start.setObjectName("start")
        self.progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progress.setGeometry(QtCore.QRect(90, 120, 511, 21))
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.line = QtWidgets.QRadioButton(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(90, 40, 89, 16))
        self.line.setAcceptDrops(False)
        self.line.setChecked(True)
        self.line.setObjectName("line")
        self.wifi = QtWidgets.QRadioButton(self.centralwidget)
        self.wifi.setGeometry(QtCore.QRect(90, 60, 89, 16))
        self.wifi.setObjectName("wifi")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 30, 401, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connectIp = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.connectIp.setObjectName("connectIp")
        self.horizontalLayout.addWidget(self.connectIp)
        self.aip = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.aip.setObjectName("aip")
        self.horizontalLayout.addWidget(self.aip)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.addname = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.addname.setObjectName("addname")
        self.horizontalLayout.addWidget(self.addname)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(200, 70, 401, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.child_dir = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.child_dir.setObjectName("child_dir")
        self.horizontalLayout_2.addWidget(self.child_dir)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(90, 160, 511, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 509, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.log_text = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.log_text.setGeometry(QtCore.QRect(0, 0, 511, 161))
        self.log_text.setObjectName("log_text")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(90, 330, 148, 32))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.make_log = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.make_log.sizePolicy().hasHeightForWidth())
        self.make_log.setSizePolicy(sizePolicy)
        self.make_log.setMinimumSize(QtCore.QSize(60, 30))
        self.make_log.setObjectName("make_log")
        self.horizontalLayout_3.addWidget(self.make_log)
        self.hour = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hour.sizePolicy().hasHeightForWidth())
        self.hour.setSizePolicy(sizePolicy)
        self.hour.setMinimumSize(QtCore.QSize(60, 20))
        self.hour.setMaximumSize(QtCore.QSize(30, 20))
        self.hour.setObjectName("hour")
        self.horizontalLayout_3.addWidget(self.hour)
        self.all_pull = QtWidgets.QCheckBox(self.centralwidget)
        self.all_pull.setGeometry(QtCore.QRect(360, 340, 71, 16))
        self.all_pull.setObjectName("all_pull")
        self.clear_all = QtWidgets.QPushButton(self.centralwidget)
        self.clear_all.setGeometry(QtCore.QRect(440, 330, 71, 31))
        self.clear_all.setObjectName("clear_all")
        self.open_dir = QtWidgets.QPushButton(self.centralwidget)
        self.open_dir.setGeometry(QtCore.QRect(520, 330, 71, 31))
        self.open_dir.setObjectName("open_dir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "i l ccg fev"))
        self.start.setToolTip(_translate("MainWindow", "连接上设备之后，点击拉取日志"))
        self.start.setText(_translate("MainWindow", "拉取"))
        self.line.setText(_translate("MainWindow", "数据线模式"))
        self.wifi.setText(_translate("MainWindow", "wifi模式"))
        self.connectIp.setToolTip(_translate("MainWindow", "点击连接对应的设备"))
        self.connectIp.setText(_translate("MainWindow", "连接IP"))
        self.aip.setPlaceholderText(_translate("MainWindow", "请设置设备ip地址"))
        self.label_2.setText(_translate("MainWindow", "备注名称"))
        self.addname.setToolTip(_translate("MainWindow", "设置备注名，上一个生成的日志拉取之后会拼接备注名"))
        self.label_3.setText(_translate("MainWindow", "子文件夹"))
        self.child_dir.setToolTip(_translate("MainWindow", "设置子文件夹的名称"))
        self.make_log.setToolTip(_translate("MainWindow", "连接上设备之后，点击生成日志"))
        self.make_log.setText(_translate("MainWindow", "生成日志"))
        self.hour.setToolTip(_translate("MainWindow", "z抓取日志的时间(小时)，不填写默认为8小时"))
        self.hour.setText(_translate("MainWindow", "8"))
        self.hour.setPlaceholderText(_translate("MainWindow", "默认8小时"))
        self.all_pull.setToolTip(_translate("MainWindow", "勾选则拉取设备端全部日志"))
        self.all_pull.setText(_translate("MainWindow", "全部log"))
        self.clear_all.setToolTip(_translate("MainWindow", "删除设备端全部日志"))
        self.clear_all.setText(_translate("MainWindow", "清除"))
        self.open_dir.setToolTip(_translate("MainWindow", "打开此程序的目录"))
        self.open_dir.setText(_translate("MainWindow", "打开目录"))


